# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da84b03460b90d502ef9ffa4cd40d056475cb463a8d087fdaa2e1a274ab530980c140838e961722f6cd310b50ac54dc3e80808058255a347aa1a820fe836985a

test:
  secret_key_base: 38a9f5b9db2ff267976f25d2116713b6ef697f97f4ac60030f65a0e646fafa7525bcc42fe97ce886782ade51a029bdd5fdd961041c2c7ea9157eeb1b0c289c71

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
